files:
  - source: /frappe/locale/main.pot
    translation: /frappe/locale/%locale_with_underscore%.po
pull_request_title: "fix: sync translations from crowdin"
pull_request_labels:
  - translation
  - skip-release-notes
commit_message: "fix: %language% translations"
append_commit_message: false
languages_mapping:
  locale_with_underscore:
    ar: ar
    bs: bs
    de: de
    eo: eo
    es-ES: es
    fa: fa
    fr: fr
    hr: hr
    hu: hu
    pl: pl
    ru: ru
    sv-SE: sv
    th: th
    tr: tr
    zh-CN: zh
